accounts/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views


app_name = 'accounts'

urlpatterns = [
    
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),

    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),

    path('login/',
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'),

    path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'),

]

strategy/urls.py
from django.urls import path
from . import views

app_name = 'strategy'


urlpatterns = [

    # トップページ表示するためにviewsのトップページ用のやつを実行する。
    path('', views.IndexView.as_view(), name='index'),

    path('post/', views.CreateStrategyView.as_view(), name='post'),

    path('post_done/',
         views.PostSuccessView.as_view(),
         name='post_done'),

    path('strategy-detail/<int:pk>',
         views.DetailView.as_view(),
         name = 'strategy_detail'
         ),

    path('strategy/<int:pk>/delete/',
         views.StrategyDeleteView.as_view(),
         name = 'strategy_delete'
         ),


    path('mypage/', views.MypageView.as_view(),
         name = 'mypage'),

    path('comment/create/<int:pk>/', views.CommentCreate.as_view(), name='comment_create'), 

    path('like_for_post/', views.like_for_post, name='like_for_post'), 

    path('contact/',views.ContactView.as_view(),name='contact'
        ),

]

strategyproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views

from django.conf import settings

from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    # strategy.urlsへのURLパターン
    path('', include('strategy.urls')),

    # accounts.urlsへのURLパターン
    path('', include('accounts.urls')),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
         name ='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"),
         name ='password_reset_done'),

    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),
         name ='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"),
         name ='password_reset_complete'),
]

urlpatterns += static(

    settings.MEDIA_URL,

    document_root=settings.MEDIA_ROOT

    )

accounts/models.py
from django.db import models


from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):

    pass

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:

        model = CustomUser

        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

class SignUpView(CreateView):

    form_class = CustomUserCreationForm

    template_name = "signup.html"

    success_url = reverse_lazy('accounts:signup_success')

    def form_valid(self, form):

        user = form.save()
        self.object = user

        return super().form_valid(form)
    
class SignUpSuccessView(TemplateView):
    
    template_name = "signup_success.html"

accounts/templates/login.html
{% load static %}

<!doctype html>

<html lang="ja">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">

    <title>Log in</title>


    <link ref="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %} />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <style>

      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }

    </style>

    <link href={% static "css/sign-in.css" %} rel="stylesheet">

  </head>

  <body class="d-flex align-items-center py-4 bg-body-tertiary text-center">
    <main class="form-signin w-100 m-auto">

      {% if form.errors %}
        <p style="color: red">ユーザー名とパスワードが一致しません。</p>
      {% endif %}

      <form method="post">

        {% csrf_token %}

        <img class="mb-4"
             src={% static "assets/img/K.png" %}
             alt="" width="72"
             height="57">

        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

        <label for="Username" class="visually-hidden">User name</label>

        <input type="text"
               name="username"
               id="id_username"
               maxlength="150"
               autocapitalize="none"
               autocomplete="username"
               class="form-control"
               placeholder="ユーザー名"
               required autofocus>
               
        <label for="Password" class="visually-hidden">Password</label>
        <input type="password"
               name="password"
               id="id_password"
               autocomplete="current-password"
               class="form-control"
               placeholder="パスワード"
               required autofocus>

          <input class="w-100 btn btn-lg btn-primary"
                 type="submit"
                 value="ログイン">

        <br><br>
        <p><a href="{% url 'password_reset' %}">パスワードを忘れましたか？</a></p>

        <input type="hidden"
               name="next"
               value="{% url 'strategy:index' %}">

      </form>
    </main>
  </body>
</html>

accounts/templates/logout.html
{% extends 'base.html' %}

{% block title %}Log out{% endblock %}


    {% block contents %}

    <div class="container">

        <div class="row">

            <div class="col offset-4 py-4">
            
            <h3>ログアウトしました</h3>

            <p><a href="{% url 'strategy:index' %}">トップページへ</a></p>


    {% endblock %}

accounts/templates/password_reset.html
{% extends 'base.html' %}

{% block title %}Reset password{% endblock %}


    {% block contents %}

    <div class="container">

        <div class="row">

            <div class="col py-4">
                <hr>
                <h3>パスワードをリセットしますか？</h3>
                <p>
                    登録済みのメールアドレスを入力してください。
                    パスワードリセットのリンクを記載したメールをすぐお届けします。
                </p>
                <br>

                <form action="" method="POST" class="text-center">
                    {% csrf_token %}

                    {{form}}

                    <input type="submit" value="メールを受け取る" /><br>
                </form>
                <br>

                <a href="{% url 'photo:index' %}">Photo Gallery</a>
                <hr>
            </div>
        </div>
    </div>
    {% endblock %}

accounts/templates/password_reset_done.html
<!DOCTYPE html>

<html lang="ja">
    <head>

        <style>
            .pad{
                background-color: lavender;
                border: solid 2px;
                padding-top: 30px;
                padding-bottom: 50px;
                padding-left: 100px;
                margin-top: 50px;
                margin-right: 70px;
                margin-left: 70px;
            }
        </style>
    </head>

    <body>
        <div class="pad">
            <h2>パスワードがリセットされました</h2>
            <p>
                Your Password has been set. You may go ahead and login
            </p>
            <br>

            <a href="{% url 'photo:index' %}">Photo Galleryのトップページ</a>
        </div>
    </body>
</html>

accounts/templates/password_reset_form.html
<!DOCTYPE html>

<html lang="ja">
    <head>

        <style>
            .pad{
                background-color: lavender;
                border: solid 2px;
                padding-top: 30px;
                padding-bottom: 50px;
                padding-left: 100px;
                margin-top: 50px;
                margin-right: 70px;
                margin-left: 70px;
            }
        </style>
    </head>

    <body>
        <div class="pad">
            <h2>Photo Gallery</h2>
            <h4>
                新しいパスワードを2回入力してください。これにより、
                正しく入力できたことが確認されます。
            </h4>
            <br />

            <form action="" method="POST">
                {% csrf_token %}

                {{form}}

                <input type="submit" value="パスワードリセット"/>
            </form>
        </div>
    </body>
</html>

accounts/templates/password_reset_sent.html
{% extends 'base.html' %}

{% block title %}Send password reset{% endblock %}


    {% block contents %}

    <hr>

    <div class="container">

        <div class="row">

            <div class="col offset-2 py-4">

                <h5>パスワードのリセット手順をメールで送信しました。
                    メールはすぐに届きます。
                </h5>

                <br>
                <h6>
                    メールが届かない場合は、登録済みメールアドレスがあるかを
                    確認し、迷惑メールフォルダーも確認してみてください。
                </h6>
                <br>

                <a href="{% url 'photo:index' %}">Photo Gallery</a>
            </div>
        </div>
    </div>

    {% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign up{% endblock %}

    {% block contents %}

    <hr>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h3>サインアップ</h3>

                <form method = "post">
                    {% csrf_token %}

                    {% for field in form %}
                        <p>

                            {{ field.label_tag }}<br>

                            {{ field }}

                            {% if field.help_text %}
                                <small style="color: grey">{{ field.help_text }}</small>

                            {% endif %}

                            {% for error in field.errors %}
                                <p style="color: red">{{ error }}</p>

                            {% endfor %}
                        </p>

                    {% endfor %}

                    <p style="color: red">
                        ※メールアドレスはパスワードをリセットする際に必要になりますので、
                        登録をお願いします。
                    </p>

                    <input type="submit" value="Sign up">
                    
                </form>

                <br>
                <p><a href="{% url 'strategy:index' %}">
                    登録をやめてトップページに戻る</a>
                </p>
            </div>
        </div>
    </div>
    
    {% endblock %}

accounts/templates/signup_success.html
{% extends 'base.html' %}

{% block title %}Registration Complete{% endblock %}

{% block contents %}

<div class="container">
    <div class="row">
        <div class="col offset-4 py4">
            <h3>登録が完了しました</h3>
            <p><a href="{% url 'accounts:login' %}">ログインはこちら</a></p>
        </div>
    </div>
</div>

{% endblock %}