accounts/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views


app_name = 'accounts'

urlpatterns = [
    
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),

    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),

    path('login/',
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'),

    path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'),

]

strategy/urls.py
from django.urls import path
from . import views

app_name = 'strategy'


urlpatterns = [

    # トップページ表示するためにviewsのトップページ用のやつを実行する。
    path('', views.IndexView.as_view(), name='index'),

    path('post/', views.CreateStrategyView.as_view(), name='post'),

    path('post_done/',
         views.PostSuccessView.as_view(),
         name='post_done'),

    path('strategy-detail/<int:pk>',
         views.DetailView.as_view(),
         name = 'strategy_detail'
         ),

    path('strategy/<int:pk>/delete/',
         views.StrategyDeleteView.as_view(),
         name = 'strategy_delete'
         ),


    path('mypage/', views.MypageView.as_view(),
         name = 'mypage'),

    path('comment/create/<int:pk>/', views.CommentCreate.as_view(), name='comment_create'), 

    path('like_for_post/', views.like_for_post, name='like_for_post'), 

    path('contact/',views.ContactView.as_view(),name='contact'
        ),

]

strategyproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views

from django.conf import settings

from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    # strategy.urlsへのURLパターン
    path('', include('strategy.urls')),

    # accounts.urlsへのURLパターン
    path('', include('accounts.urls')),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
         name ='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"),
         name ='password_reset_done'),

    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),
         name ='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"),
         name ='password_reset_complete'),
]

urlpatterns += static(

    settings.MEDIA_URL,

    document_root=settings.MEDIA_ROOT

    )

strategy/models.py
from django.db import models

from accounts.models import CustomUser

from django.utils import timezone

class Category(models.Model):

    title = models.CharField(
        verbose_name='カテゴリ',
        max_length=20
    )


    def __str__(self):

        return self.title
    
    
class StrategyPost(models.Model):

    user = models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE
    )

    category = models.ForeignKey(
        Category,
        verbose_name='カテゴリ',

        on_delete=models.PROTECT
    )


    title = models.CharField(
        verbose_name='タイトル',
        max_length=200
    )

    comment1 = models.TextField(
        verbose_name='コメント1',
    )

    comment2 = models.TextField(
        verbose_name='コメント2',
        blank=True,
        null=True,
    )

    comment3 = models.TextField(
        verbose_name='コメント3',
        blank=True,
        null=True,

    )

    image1 = models.ImageField(
        verbose_name='イメージ1',
        upload_to= 'photos'
    )

    image2 = models.ImageField(
        verbose_name='イメージ2',
        upload_to= 'photos',
        blank=True,
        null=True,

    )

    image3 = models.ImageField(
        verbose_name='イメージ3',
        upload_to= 'photos',
        blank=True,
        null=True,
    )

    posted_at = models.DateField(
        verbose_name='投稿日時',
        auto_now_add=True
    )

    def __str__(self):

        return self.title
    
class Comment(models.Model):
    """記事に紐づくコメント"""
    name = models.CharField('名前', max_length=255, default='名無し')
    text = models.TextField('本文')
    target = models.ForeignKey(StrategyPost, on_delete=models.CASCADE, verbose_name='対象記事')
    created_at = models.DateTimeField('作成日', default=timezone.now)
 
    def __str__(self):
        return self.text[:20]
    
class LikeForPost(models.Model):
    """投稿に対するいいね"""
    target = models.ForeignKey(StrategyPost, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=timezone.now)

class LikeForComment(models.Model):
    """コメントに対するいいね"""
    target = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=timezone.now)

strategy/forms.py
from django.forms import ModelForm
from .models import StrategyPost, Comment

from django import forms

class StrategyPostForm(ModelForm):

    class Meta:


        model = StrategyPost

        fields = ['category','title', 'comment1', 'comment2', 'comment3', 'image1', 'image2', 'image3']

class CommentCreateForm(ModelForm):
    """コメントフォーム"""
    class Meta:
        model = Comment
        exclude = ('target', 'created_at')

class ContactForm(forms.Form):

  name = forms.CharField(label='お名前')
  email = forms.CharField(label='メールアドレス')
  title = forms.CharField(label='件名')
  message = forms.CharField(label='メッセージ', widget=forms.Textarea)

  def __init__(self, *args, **kwargs):

      super().__init__(*args, **kwargs)

      self.fields['name'].widget.attrs['placeholder'] = \
        'お名前を入力してください'
      
      self.fields['name'].widget.attrs['class'] = 'form-control'

      self.fields['email'].widget.attrs['placeholder'] = \
        'メールアドレスを入力してください'
      
      self.fields['email'].widget.attrs['class'] = 'form-control'

      self.fields['title'].widget.attrs['placeholder'] = \
        'タイトルを入力してください'
      
      self.fields['title'].widget.attrs['class'] = 'form-control'

      self.fields['message'].widget.attrs['placeholder'] = \
        'メッセージを入力してください'
      
      self.fields['message'].widget.attrs['class'] = 'form-control'

strategy/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.views.generic import TemplateView, ListView, FormView, CreateView

from django.urls import reverse_lazy

from .forms import StrategyPostForm, CommentCreateForm ,ContactForm

from django.utils.decorators import method_decorator

from django.contrib.auth.decorators import login_required

from .models import StrategyPost, Comment, LikeForPost

from django.views.generic import DetailView

from django.views.generic import DeleteView

from django.http import JsonResponse

from django.contrib import messages

from django.core.mail import EmailMessage


class ContextMixin:
    """
    get_context_data()で受け取ったキーワード引数をテンプレート・コンテキストとして渡す
    """
    extra_context = None

    def get_context_data(self, **kwargs):
        kwargs.setdefault('view', self) # key:'view'が無い時、value:selfを追加
        if self.extra_context is not None:
            kwargs.update(self.extra_context) # extra_contextがある時、kwargsに上書き
        return kwargs


class IndexView(ListView):

    template_name ='index.html'

    queryset = StrategyPost.objects.order_by('-posted_at')

    paginate_by = 3


@method_decorator(login_required, name='dispatch')
class CreateStrategyView(CreateView):

    form_class = StrategyPostForm

    template_name = "post_strategy.html"

    success_url = reverse_lazy('strategy:post_done')

    def form_valid(self, form):

        postdata = form.save(commit=False)

        postdata.user = self.request.user

        postdata.save()

        return super().form_valid(form)
    
class PostSuccessView(TemplateView):

    template_name = 'post_success.html'

class DetailView(DetailView):

    template_name ='detail.html'

    model = StrategyPost

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(StrategyPost, pk=self.kwargs['pk'])
        detail = StrategyPost.objects.filter(pk=self.kwargs['pk']).order_by("-id").first()
        context['comments'] =Comment.objects.filter(target=detail.id)



        like_for_post_count = self.object.likeforpost_set.count()
        context['like_for_post_count'] = like_for_post_count
        if self.object.likeforpost_set.filter(user=self.request.user).exists():
            context['is_user_liked_for_post'] = True
        else:
            context['is_user_liked_for_post'] = False

        return context




class StrategyDeleteView(DeleteView):


    model = StrategyPost

    template_name ='strategy_delete.html'

    success_url = reverse_lazy('strategy:index')

    def delete(self, request, *args, **kwargs):
        
        return super().delete(request, *args, **kwargs)
    

    
        
class MypageView(ListView):


    template_name ='mypage.html'

    paginate_by = 3

    def get_queryset(self):

        queryset = StrategyPost.objects.filter(
            user=self.request.user).order_by('-posted_at')
        
        return queryset
    


class CommentCreate(CreateView):
    """コメント投稿ページのビュー"""
    template_name = 'comment_form.html'
    model = Comment
    form_class = CommentCreateForm
 
    def form_valid(self, form):
        post_pk = self.kwargs['pk']
        post = get_object_or_404(StrategyPost, pk=post_pk)
        comment = form.save(commit=False)
        comment.target = post
        comment.save()

        return redirect('strategy:strategy_detail', pk=post_pk)
    

 
def like_for_post(request):
    post_pk = request.POST.get('post_pk')
    context = {
        'user': f'{request.user.last_name} {request.user.first_name}',
    }
    post = get_object_or_404(StrategyPost, pk=post_pk)
    like = LikeForPost.objects.filter(target=post, user=request.user)

    if like.exists():
        like.delete()
        context['method'] = 'delete'
    else:
        like.create(target=post, user=request.user)
        context['method'] = 'create'

    context['like_for_post_count'] = post.likeforpost_set.count()

    return JsonResponse(context)

class ContactView(FormView):

    template_name ='contact.html'

    form_class = ContactForm

    success_url = reverse_lazy('strategy:contact')

    def form_valid(self, form):

        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']

        subject = 'お問い合わせ: {}'.format(title)

        message = \
        '送信者名 : {0}\nメールアドレス : {1}\n\n タイトル : {2}\n\n メッセージ :\n{3}' \
        .format(name, email ,title, message)

        from_email = 'masaori09040911@gmail.com'

        to_list = ['masaori09040911@gmail.com']

        message = EmailMessage(subject=subject,
                               body=message,
                               from_email=from_email,
                               to=to_list,
                               )

        message.send()

        messages.success(
            self.request, 'お問い合わせは正常に送信されました。')
        

        return super().form_valid(form)

strategy/templates/base.html
<!-- お馴染みのstatic。静的ファイルのURLを生成するため -->
{% load static %}

<!doctype html>
<html lang="js" data-bs-theme="auto">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.112.5">

    <!-- タイトルを各ページのテンプレートで表示する -->
    <title>{% block title %}{% endblock %}</title>


    

    

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">  

    

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>

    

    <!-- 多分ここのcssはサイトの奴じゃなくて同梱のcssファイルなので。 -->
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">

    <!-- 個人的に設定するようのCSS -->
    <link href="{% static 'css/mysetting.css' %}" rel="stylesheet">


    {% block extrahead %}{% endblock %}

  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>


    <!-- これ多分、全画面以外の時用のドロップダウンのやつ。 -->
    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>

    
<header data-bs-theme="dark">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">

      <!-- トップページ(左上のサイトアイコン的なやつ)のリンク -->
      <a class="navbar-brand" href="{% url 'strategy:index' %}">Strategysite</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">

          <!-- ナビゲーションにある諸々のリンク -->

          {% if user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'strategy:index' %}">Home</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">logout</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'strategy:mypage' %}">mypage</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'strategy:contact' %}">contact</a>
          </li>

          {% else %}

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'strategy:index' %}">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">login</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">signin</a>
          </li>

          {% endif %}
          
        </ul>
      </div>
    </div>
  </nav>
</header>

<main>
  
  {% block contents %}{% endblock %}

  <!-- FOOTER -->
  <footer class="container">

    <!-- トップページへのリンクの変更 -->
    <p class="float-end"><a href="{% url 'strategy:index' %}">Back to top</a></p>
    <p>&copy; Strategysite, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
      {% block extrajs %}{% endblock %}
    </body>
</html>

strategy/templates/comment_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}strategy comment{% endblock %}

    {% block contents %}
    <div class="container col-lg-6 offset-lg-3">
        <p class="titleline">{{ post.title }}</p>
        <form action="" method="POST" id="comment-form">
            {{ form.non_field_errors }}
            {% for field in form %}
            <div class="field">
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
        
                {{ field.errors }}
            </div>
            {% endfor %}

            {% csrf_token %}
            <div class="row my-3">
                <button type="submit" class="btn btn-success col-3 offset-2">送信する</button>
                <a class="btn btn-danger col-3 offset-2" href="{% url 'strategy:index'%}">ホームへ</a>
            </div>
        </form>
    </div>
    {% endblock %}

strategy/templates/index.html
{% extends 'base.html' %}

{% block title %}Strategy site{% endblock %}

  
  {% block contents %}

  {% include "strategy_carousel_item.html" %}

  {% include "strategy_Heding.html" %}

  {% include "strategy_list.html" %}

  {% include "pagination.html" %}

  {% endblock %}

strategy/templates/mypage.html
{% extends 'base.html' %}

{% block title %}Mypage{% endblock %}

    {% block contents %}

    {% if user.is_authenticated %}
        <br>
        <div style="text-align:center">
            <h4>{{user.username}}さんのマイページ</h4>
            {% if object_list.count == 0 %}
                <p>{{username}}さんの投稿はありません</p>
            {% else %}
                <p>投稿<strong>{{object_list.count}}</strong>件</p>
            {% endif %}
            <a href="{% url 'strategy:post' %}">投稿する</a>
        </div>
        <hr>
    {% endif %}
    
    <div class="container marketing">
        {% include "strategy_list.html" %}

        {% include "pagination.html" %}
    </div>

    {% endblock %}

strategy/templates/post_success.html
{% extends 'base.html' %}

{% block title %}Post Success{% endblock %}

    {% block contents %}

    <br><br>
    <div class="container">
        <div class="row">

            <div class="col offset-2">
                <h4>投稿が完了しました!</h4>
            </div>
        </div>
    </div>

    {% endblock %}

strategy/templates/strategy_Heding.html
{% load static %}

<div class="container marketing">
    <div class="row">
        

        {% if user.is_authenticated %}
        <div class="col-lg-4">
        <img src="{% static 'assets/img/ログアウト.png' %}" class="bd-placeholder-img rounded-circle" width="140" height="140" role="img" focusable="false">
        <h2 class="fw-normal">ログアウト</h2>
        <p>ログアウトしてしまうのですか？</p>
        <p><a class="btn btn-danger" href="{% url 'accounts:logout' %}">ログアウトはこちらから &raquo;</a></p>
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-4">
        <img src="{% static 'assets/img/マイページ.png' %}" class="bd-placeholder-img rounded-circle" width="140" height="140" role="img" focusable="false">
        <h2 class="fw-normal">マイページ</h2>
        <p>自分の投稿を確認しよう</p>
        <p><a class="btn btn-warning" href="{% url 'strategy:mypage' %}">マイページはこちらから &raquo;</a></p>
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-4">
        <img src="{% static 'assets/img/投稿.png' %}" class="bd-placeholder-img rounded-circle" width="140" height="140" role="img" focusable="false">
        <h2 class="fw-normal">投稿</h2>
        <p>攻略情報を世界に共有しよう</p>
        <p><a class="btn btn-dark" href="{% url 'strategy:post' %}">投稿ページはこちらから &raquo;</a></p>
        </div><!-- /.col-lg-4 -->

        {% else %}

        <div class="col-lg-4">
        <img src="{% static 'assets/img/サインイン.png' %}" class="bd-placeholder-img rounded-circle" width="140" height="140" role="img" focusable="false">
        <h2 class="fw-normal">サインイン</h2>
        <p>アカウントを登録すれば、攻略情報の閲覧や情報の投稿が出来ます。</p>
        <p><a class="btn btn-success" href="{% url 'accounts:signup' %}">サインインはこちらから &raquo;</a></p>
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-4">
        <img src="{% static 'assets/img/ログイン.png' %}" class="bd-placeholder-img rounded-circle" width="140" height="140" role="img" focusable="false">
        <h2 class="fw-normal">ログイン</h2>
        <p>ログインをして、攻略情報を投稿しよう</p>
        <p><a class="btn btn-info" href="{% url 'accounts:login' %}">ログインはこちらから &raquo;</a></p>
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-4">
        <img src="{% static 'assets/img/投稿.png' %}" class="bd-placeholder-img rounded-circle" width="140" height="140" role="img" focusable="false">
        <h2 class="fw-normal">投稿</h2>
        <p>投稿機能はログイン状態でないと使用できません！</p>
        </div><!-- /.col-lg-4 -->
        {% endif %}

        
    </div><!-- /.row -->